# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivity',
            name='steps_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='water',
            name='water_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodsugar',
            name='mg_dL',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='insulin',
            name='mcU_ml',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, choices=[('AI', 'American Indian'), ('A', 'Asian'), ('AA', 'African American'), ('NH', 'Native Hawaiian'), ('W', 'White')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
