# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsugar',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insulin',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
