# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0002_auto_20161227_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsugar',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='insulin',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='time_eaten',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='water',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
