# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0002_auto_20170106_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalactivity',
            name='steps_goal',
        ),
        migrations.RemoveField(
            model_name='water',
            name='water_goal',
        ),
        migrations.AddField(
            model_name='profile',
            name='steps_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='water_goal',
            field=models.IntegerField(default=0),
        ),
    ]
