# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0003_auto_20161229_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/avatars/', verbose_name='profile picture'),
        ),
    ]
