# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0006_auto_20170106_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='calories_burned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
