# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0007_auto_20170109_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
