# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0008_auto_20170109_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, choices=[('AI', 'American Indian'), ('A', 'Asian'), ('AA', 'African American'), ('L', 'Latino'), ('ME', 'Middle Eastern'), ('SA', 'South Asian/Indian'), ('NH', 'Native Hawaiian'), ('W', 'White')], max_length=2, null=True),
        ),
    ]
