# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0011_auto_20170113_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
