# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0013_auto_20170117_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalactivity',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='physicalactivity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
