# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabeatthis', '0017_merge_20170206_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
